In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [2]:
turbine=pd.read_csv("C:\\Users\\ASUS\\Downloads\\DATA SCIENCE\\ASSIGNMENTS\\Neural Networks\\gas_turbines.csv")
turbine.head()

AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0  6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  114.70  10.605   
1  6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  114.72  10.598   
2  6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  114.71  10.601   
3  7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  114.72  10.606   
4  7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  114.72  10.612   

       CO     NOX  
0  3.1547  82.722  
1  3.2363  82.776  
2  3.2012  82.468  
3  3.1923  82.670  
4  3.2484  82.311

In [3]:
turbine.shape

(15039, 11)

In [4]:
turbine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15039 entries, 0 to 15038
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      15039 non-null  float64
 1   AP      15039 non-null  float64
 2   AH      15039 non-null  float64
 3   AFDP    15039 non-null  float64
 4   GTEP    15039 non-null  float64
 5   TIT     15039 non-null  float64
 6   TAT     15039 non-null  float64
 7   TEY     15039 non-null  float64
 8   CDP     15039 non-null  float64
 9   CO      15039 non-null  float64
 10  NOX     15039 non-null  float64
dtypes: float64(11)
memory usage: 1.3 MB


In [5]:
# As we have to convert the TEY column into categorical column so need to calculate the mean first and then using lambda function categorize that column into 0's and 1's according to the mean
turbine_mean = turbine.TEY.mean()
turbine_mean

134.18846399361655

In [6]:
turbine['performance'] = turbine.TEY.map(lambda x: 1 if x > 134 else 0)

In [7]:
turbine.performance

0        0
1        0
2        0
3        0
4        0
        ..
15034    0
15035    0
15036    0
15037    0
15038    0
Name: performance, Length: 15039, dtype: int64

In [8]:
turbine.performance.value_counts()

0    8484
1    6555
Name: performance, dtype: int64

In [9]:
turbine

AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0      6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  114.70  10.605   
1      6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  114.72  10.598   
2      6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  114.71  10.601   
3      7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  114.72  10.606   
4      7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  114.72  10.612   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
15034  9.0301  1005.6  98.460  3.5421  19.164  1049.7  546.21  111.61  10.400   
15035  7.8879  1005.9  99.093  3.5059  19.414  1046.3  543.22  111.78  10.433   
15036  7.2647  1006.3  99.496  3.4770  19.530  1037.7  537.32  110.19  10.483   
15037  7.0060  1006.8  99.008  3.4486  19.377  1043.2  541.24  110.74  10.533   
15038  6.9279  1007.2  97.533  3.4275  19.306  1049.9  545.85  111.58  10.583   

           CO     NOX  performance  
0      3.1547  82.722            0  
1      3.2363  82.776            0  
2      3.2012  82.468            0  
3      3.1923  82.670            0  
4      3.2484  82.311            0  
...       ...     ...          ...  
15034  4.5186  79.559            0  
15035  4.8470  79.917            0  
15036  7.9632  90.912            0  
15037  6.2494  93.227            0  
15038  4.9816  92.498            0  

[15039 rows x 12 columns]

In [10]:
turbine.drop(['TEY'],inplace=True,axis=1)

In [11]:
turbine

AT      AP      AH    AFDP    GTEP     TIT     TAT     CDP      CO  \
0      6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  10.605  3.1547   
1      6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  10.598  3.2363   
2      6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  10.601  3.2012   
3      7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  10.606  3.1923   
4      7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  10.612  3.2484   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
15034  9.0301  1005.6  98.460  3.5421  19.164  1049.7  546.21  10.400  4.5186   
15035  7.8879  1005.9  99.093  3.5059  19.414  1046.3  543.22  10.433  4.8470   
15036  7.2647  1006.3  99.496  3.4770  19.530  1037.7  537.32  10.483  7.9632   
15037  7.0060  1006.8  99.008  3.4486  19.377  1043.2  541.24  10.533  6.2494   
15038  6.9279  1007.2  97.533  3.4275  19.306  1049.9  545.85  10.583  4.9816   

          NOX  performance  
0      82.722            0  
1      82.776            0  
2      82.468            0  
3      82.670            0  
4      82.311            0  
...       ...          ...  
15034  79.559            0  
15035  79.917            0  
15036  90.912            0  
15037  93.227            0  
15038  92.498            0  

[15039 rows x 11 columns]

In [12]:
turbine.shape

(15039, 11)

In [13]:
# Splitting the data into x and y as input and output

x= turbine.iloc[:,0:10]
y= turbine.iloc[:,10]

In [14]:
x

AT      AP      AH    AFDP    GTEP     TIT     TAT     CDP      CO  \
0      6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  10.605  3.1547   
1      6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  10.598  3.2363   
2      6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  10.601  3.2012   
3      7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  10.606  3.1923   
4      7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  10.612  3.2484   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
15034  9.0301  1005.6  98.460  3.5421  19.164  1049.7  546.21  10.400  4.5186   
15035  7.8879  1005.9  99.093  3.5059  19.414  1046.3  543.22  10.433  4.8470   
15036  7.2647  1006.3  99.496  3.4770  19.530  1037.7  537.32  10.483  7.9632   
15037  7.0060  1006.8  99.008  3.4486  19.377  1043.2  541.24  10.533  6.2494   
15038  6.9279  1007.2  97.533  3.4275  19.306  1049.9  545.85  10.583  4.9816   

          NOX  
0      82.722  
1      82.776  
2      82.468  
3      82.670  
4      82.311  
...       ...  
15034  79.559  
15035  79.917  
15036  90.912  
15037  93.227  
15038  92.498  

[15039 rows x 10 columns]

In [15]:
y

0        0
1        0
2        0
3        0
4        0
        ..
15034    0
15035    0
15036    0
15037    0
15038    0
Name: performance, Length: 15039, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
# Splitting the data into training and test dataset

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=0)

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

StandardScaler()

In [19]:
# Now apply the transformations to the data:
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [20]:
from sklearn.neural_network import MLPClassifier

In [21]:
mlp = MLPClassifier(hidden_layer_sizes=(30,30))

In [22]:
mlp.fit(x_train,y_train)

MLPClassifier(hidden_layer_sizes=(30, 30))

In [23]:
prediction_train=mlp.predict(x_train)
prediction_test = mlp.predict(x_test)

In [24]:
prediction_test

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [25]:
prediction_train

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [26]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,prediction_test))
np.mean(y_test==prediction_test)
np.mean(y_train==prediction_train)

[[2392  148]
 [ 170 1802]]


0.9391089579177353

# With  Backpropogation 

In [27]:
# Create your first MLP in Keras
from keras.models import Sequential
from keras.layers import Dense
import numpy
#pip install keras
#https://www.tensorflow.org/install/pip#windows

In [32]:
# create model
model = Sequential()
model.add(Dense(12, input_dim=10, activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [33]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [34]:
# Fit the model
model.fit(x,y, validation_split=0.33, epochs=150, batch_size=10)

Epoch 1/150
1008/1008 [==============================] - 3s 2ms/step - loss: 1.7299 - accuracy: 0.7130 - val_loss: 0.5000 - val_accuracy: 0.7227
Epoch 2/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.4436 - accuracy: 0.7709 - val_loss: 0.4024 - val_accuracy: 0.7538
Epoch 3/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.4186 - accuracy: 0.7790 - val_loss: 0.3602 - val_accuracy: 0.7767
Epoch 4/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3949 - accuracy: 0.7893 - val_loss: 0.3421 - val_accuracy: 0.8338
Epoch 5/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3856 - accuracy: 0.7904 - val_loss: 0.3019 - val_accuracy: 0.8551
Epoch 6/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3751 - accuracy: 0.8007 - val_loss: 0.3034 - val_accuracy: 0.8434
Epoch 7/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3796 - accuracy: 0.7943 - val_loss: 0.3310 - val_ac

1008/1008 [==============================] - 2s 2ms/step - loss: 0.3242 - accuracy: 0.8224 - val_loss: 0.2571 - val_accuracy: 0.8527
Epoch 58/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3192 - accuracy: 0.8291 - val_loss: 0.3040 - val_accuracy: 0.8432
Epoch 59/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3231 - accuracy: 0.8266 - val_loss: 0.2963 - val_accuracy: 0.8432
Epoch 60/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3251 - accuracy: 0.8252 - val_loss: 0.2550 - val_accuracy: 0.8549
Epoch 61/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3123 - accuracy: 0.8329 - val_loss: 0.2812 - val_accuracy: 0.8003
Epoch 62/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3185 - accuracy: 0.8278 - val_loss: 0.3116 - val_accuracy: 0.8432
Epoch 63/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3222 - accuracy: 0.8228 - val_loss: 0.2557 - val_accuracy

1008/1008 [==============================] - 2s 2ms/step - loss: 0.3213 - accuracy: 0.8319 - val_loss: 0.2648 - val_accuracy: 0.8523
Epoch 114/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3109 - accuracy: 0.8360 - val_loss: 0.2397 - val_accuracy: 0.8644
Epoch 115/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3140 - accuracy: 0.8301 - val_loss: 0.2317 - val_accuracy: 0.8783
Epoch 116/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3114 - accuracy: 0.8324 - val_loss: 0.2572 - val_accuracy: 0.8535
Epoch 117/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3072 - accuracy: 0.8374 - val_loss: 0.2287 - val_accuracy: 0.8932
Epoch 118/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3206 - accuracy: 0.8365 - val_loss: 0.2467 - val_accuracy: 0.8890
Epoch 119/150
1008/1008 [==============================] - 2s 2ms/step - loss: 0.3021 - accuracy: 0.8410 - val_loss: 0.2638 - val_ac

In [35]:
# evaluate the model
scores = model.evaluate(x,y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

470/470 [==============================] - 1s 821us/step - loss: 0.2844 - accuracy: 0.8382
accuracy: 83.82%
